name: Deploy Medusa to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore Terraform state
      uses: actions/download-artifact@v2
      with:
        name: terraform-state
        path: ./terraform

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin 841162667281.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build the Docker image
      run: docker build -t medusa-app .

    - name: Tag the Docker image for ECR
      run: docker tag medusa-app:latest 841162667281.dkr.ecr.us-east-1.amazonaws.com/medusa-app-repo:latest

    - name: Push the image to ECR
      run: docker push 841162667281.dkr.ecr.us-east-1.amazonaws.com/medusa-app-repo:latest

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

    - name: Deploy to ECS with Terraform
      run: terraform apply -auto-approve
      working-directory: ./terraform

    - name: Upload Terraform state
      uses: actions/upload-artifact@v2
      with:
        name: terraform-state
        path: ./terraform/terraform.tfstate
