name: Deploy Medusa to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get AWS Account ID
      run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build the Docker image
      run: docker build -t medusa-app .

    - name: Tag the Docker image for ECR
      run: docker tag medusa-app:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/medusa-app-repo:latest

    - name: Push the image to ECR
      run: docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/medusa-app-repo:latest

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Deploy to ECS with Terraform
      run: terraform apply -auto-approve
